### DISCUSSION TITLE
help me with tap menu ,react prime ?

### DISCUSSION THREAD

**Discussion by MoAlghorbani** [primefaces/community#1104] [PrimeReact] [answered]
yo guys , iam new to reactprime , i just want to know how can i change the color of the selected item in TabMenu ?

**Comment by melloware** [comment, marked as answer]
use this CSS to change the color..

```css
.p-tabmenu .p-tabmenu-nav .p-tabmenuitem.p-highlight .p-menuitem-link {
    background: #ffffff;
    border-color: #6366f1;
    color: #6366f1;
}
```
