### DISCUSSION TITLE
[Feature Request] ProgressSpinner  should have a color prop to control it's color

### DISCUSSION THREAD

**Discussion by douglasg14b** [primefaces/community#1283] [PrimeVue]
The ergonomics of this are less than ideal, especially with the default being rainbow colored, instead of a color prop to control the stroke, css has to be used instead like:

Ideally the component is "vue like" in that it supports props for it's configurable parameters like color.

Thanks!

```scss
.p-progress-spinner {
  .p-progress-spinner-circle {
    stroke: var(--purple-700) !important;
  }
}
```
