### DISCUSSION TITLE
Accordion: While an animation is in progress, the animation is interrupted

### DISCUSSION THREAD

**Discussion by KumJungMin** [primefaces/community#1424] [PrimeVue] [answered]
### Suggestion
- If I click a button while an animation is in progress, the animation is interrupted.

https://github.com/primefaces/community/assets/37934668/fe67780f-2335-4e4e-a623-55419280296c

- current, Accordion animation is only css.
- but css can not resolve temporary animation stop problem.

```css
/* primevue/public/themes/nova/theme.css */

/* Toggleable Content */
.p-toggleable-content-enter-from,
.p-toggleable-content-leave-to {
  max-height: 0;
}

.p-toggleable-content-enter-to,
.p-toggleable-content-leave-from {
  max-height: 1000px;
}

.p-toggleable-content-leave-active {
  overflow: hidden;
  transition: max-height 0.45s cubic-bezier(0, 1, 0, 1);
}

.p-toggleable-content-enter-active {
  overflow: hidden;
  transition: max-height 1s ease-in-out;
}
```

<br/> 

- So, i suggest, to use requestAnimationFrame on v-transition event.
- requestAnimationFrame can resolve on temporary animation stop problem.
```js

onEnter(el: HTMLExpandElement) {
    // set maxHeight value
    requestAnimationFrame(() => {
      el.style.maxHeight = offset;
    })
  },

onAfterEnter(el: HTMLExpandElement) {
  // reset maxHeight value to cover resizing
	el.style.maxHeight = 'fit-content';
},

onLeave(el: HTMLExpandElement) {
     // change maxHeight to an integer value.(required to apply animation)
    el.style.maxHeight = offset;
	
     // and, change requestAnimationFrame to 0.
    requestAnimationFrame(() => (el.style.maxHeight = '0'))
  }
}
```
