### DISCUSSION TITLE
Steps Component has two 'background" properties in Diamond Theme

### DISCUSSION THREAD

**Discussion by sanfordandrew** [primefaces/community#1784] [PrimeReact Templates]
In the Diamond theme, the steps component has a typo, I believe.  The background property is given twice.  The correct background should be transparent.  Since #ffffff (white) appears second, it overrides the correct transparent setting.   Easy enough to correct, but thought I'd mention it for future correction...

Thanks,

Andrew

```css
 .p-steps .p-steps-item .p-menuitem-link {
    background: transparent;
    transition: box-shadow 0.2s;
    border-radius: 4px;
    background: #ffffff;
  }
```
