### DISCUSSION TITLE
p:datePicker  - how to align text to center?

### DISCUSSION THREAD

**Discussion by JeeDevUser** [primefaces/community#1985] [PrimeFaces] [answered]
Hi all,

Is there a way to align text (ie, date)  of p:datePicker to be in the center?

**Comment by melloware** [comment, marked as answer]
Try this CSS

```css
body .p-datepicker > input {
  text-align: center;
}
```
