### DISCUSSION TITLE
MultiSelect and TreeSelect: How to remove or hide checkboxes and icons + empty area ?

### DISCUSSION THREAD

**Discussion by Oleksandr-Markovskyi** [primefaces/community#208] [PrimeVue] [answered]
Hello,
Component MultiSelect (and TreeSelect). 
Howe I can remove or hide checkboxes without hardcode ?

Component TreeSelect. 
Howe I can remove or hide icons without hardcode?

Example. I created some code:
`export const NodeService = {
  getTreeNodesData() {
    return [
    {
        key: "1",
        label: "Events 1",
        data: "Events Folder",
      },
      {
        key: "2",
        label: "Events 2",
        data: "Events Folder",
      }, ....`
      
without "icons: ..." . It's work, but I can't remove empty area on right side (where was icon)

Thanks for your time :)

**Comment by FlipWarthog** [comment, marked as answer]
Not sure what you mean by "without hardcode" but you can do it with some CSS:
```css
body .p-treenode-icon {
  display: none;
}
body .p-multiselect-header .p-checkbox,
body .p-multiselect-item .p-checkbox {
  display: none;
}
body .p-multiselect-header {
  flex-direction: row-reverse;
}
```

Example: https://stackblitz.com/edit/8aarvp?file=src%2Fstyle.css,src%2FApp.vue
