### DISCUSSION TITLE
Ultima: triStateCheckbox State Icon does not change

### DISCUSSION THREAD

**Discussion by roabol** [primefaces/community#2116] [PrimeFaces Templates] [answered]
Hello. 

I'm trying to use the p:triStateCheckbox component, and I found a problem in the ULTIMA theme. The icons for stateOneIcon, stateTwoIcon and stateThreeIcon are not differentiating. I added the component to the ultima showcase project and the problem occurred.

`<h5>triStateCheckBox</h5>`
`<p:triStateCheckbox />`

![image](https://github.com/primefaces/community/assets/2237805/79e2ddab-8eba-4163-b53f-4b9ae0180b1c)

**Comment by roabol** [comment]
PF 14.0.0 and version 7.0.0 of ultima.

**Reply by melloware** [reply, marked as answer]
Yep its a bug.  
![image](https://github.com/primefaces/community/assets/4399574/842f0505-eead-4cf3-bfe4-1b726e66861a)


I just tested with my local Ultima and fixed it by editing `\ultima\src\main\webapp\resources\layout\styles\theme\extensions\_checkbox.scss`

and making the file just this

```css
body {
  .ui-chkbox {
    border-radius: 50%;
    transition: box-shadow $transitionDuration;

    .ui-chkbox-box {
      border-color: nth($checkboxBorder, 3);
      border-radius: 2px;
      position: relative;

      &:not(.ui-state-disabled).ui-state-hover {
        border-color: nth($checkboxBorder, 3);
      }

      &:not(.ui-state-disabled).ui-state-focus {
        border-color: nth($checkboxBorder, 3);
      }

      &.ui-state-active {
        &:not(.ui-state-disabled).ui-state-hover {
          border-color: $checkboxActiveBorderColor;
        }

        &:not(.ui-state-disabled).ui-state-focus {
          border-color: $checkboxActiveBorderColor;
        }
      }
    }

    &:has(:not(.ui-state-disabled).ui-state-hover) {
      // box-shadow: 0 0 1px 10px rgba($overlayColor, .04);
    }

    &:has(:not(.ui-state-disabled).ui-state-focus) {
      // box-shadow: 0 0 1px 10px rgba($overlayColor, .12);
    }

    &:has(.ui-state-active) {
      &:has(:not(.ui-state-disabled).ui-state-hover) {
        // box-shadow: 0 0 1px 10px rgba($checkboxActiveBg, .04);
      }
  
      &:has(:not(.ui-state-disabled).ui-state-focus) {
        // box-shadow: 0 0 1px 10px rgba($checkboxActiveBg, .12);
      }
    }

    &.ui-input-filled, .ui-input-filled {
      .ui-chkbox {
        .ui-chkbox-box {
          background-color: $inputBg;

          &:not(.ui-state-disabled):not(.ui-state-active).ui-state-hover {
            background-color: $inputBg;
          }
        }
      }
    }
  }
}

@keyframes checkbox-check {
  0%{
    width: 0;
    height: 0;
    border-color: $checkboxTextActiveColor;
    transform: translate3d(0,0,0) rotate(45deg);
  }
  33%{
    width: 4px;
    height: 0;
    transform: translate3d(0,0,0) rotate(45deg);
  }
  100%{    
    width: 4px;
    height: 10px;    
    border-color: $checkboxTextActiveColor;
    transform: translate3d(0,-10px,0) rotate(45deg);
  }
}
```
