### DISCUSSION TITLE
How can I add alpha value to the palette colors?

### DISCUSSION THREAD

**Discussion by oliver139** [primefaces/community#2306] [PrimeVue]
I am configure the color theme:
```css
::selection {
  background: var(--p-primary-color);
}
```

What if I want to add some transparency to it?

**Comment by yuexiawod** [comment]
I need to add some new features to the color picker:
1. alpha
2. Predefined colors

**Comment by oliver139** [comment]
> I need to add some new features to the color picker:
> 1. alpha
> 2. Predefined colors

Give it up, I don't think there is a solution. No one here / in discord can answer this..

If you need a easy workaround
Copy the color set RGB value to a custom css file like:
```css
html {
 --red: 255 0 0;
}
```

Then use it like
```css
.box {
  background: rgb(var(--red) / 50%);
}
```
