### DISCUSSION TITLE
Ultima theme - Wrong resource path: accessDenied-bg.jpg

### DISCUSSION THREAD

**Discussion by erickdeoliveiraleal** [primefaces/community#2366] [PrimeFaces Templates] [answered]
The files /ultima/src/main/webapp/resources/demo/styles/demo.css and /ultima/src/main/webapp/resources/demo/styles/auth/_access.scss
reference the wrong path of accessDenied-bg.jpg

**Comment by melloware** [comment, marked as answer]
in `_access.scss` change to the following: 

```css
.pages-body {
    &.accessdenied-page {
        background: url("\#{resource['demo:images/pages/401.svg']}");
        background-size: cover;

        .pages-panel {
            .pages-header {
                background: #FB8C00;
            }
        }
    }
}
```
