### DISCUSSION TITLE
SelectOneMenu elements look different in tables than usual.

### DISCUSSION THREAD

**Discussion by hgfrey** [primefaces/community#2457] [PrimeFaces] [answered]
Is it intentional for SelectOneMenu items to look different in tables than outside of tables? This has been the case since version 14.0.0.

![image](https://github.com/user-attachments/assets/bd6cb64e-7e97-40e4-b5ca-1c09b2405aae)

**Comment by melloware** [comment]
Looks like you are missing some CSS.  What theme are you using?

**Reply by hgfrey** [reply]
We use our own theme.

It looks like a style specification in component.css is responsible for the border:
![image](https://github.com/user-attachments/assets/0c9c34b5-9406-4fac-8c09-09c4fdaa732e)

**Reply by melloware** [reply]
yep you can either fix your CSS or set `cellNavigation="false"` on the datatable.

**Reply by hgfrey** [reply]
component.css is from PrimeFaces, right?

**Reply by melloware** [reply, marked as answer]
yes what you are getting the the `:focus` selector for the cell being focused by `cellNavigation="true"` which is the default. See: https://github.com/primefaces/primefaces/issues/11783#issuecomment-2115351352

If you don't want that simple disable it with `cellNavigation="false"` on your datatable.

**Reply by hgfrey** [reply]
I'll try this out. Thanks. 

Why do the SelectOneMenu elements with focus in a table look different by default than in a form?

**Reply by melloware** [reply]
its right in your screenshot above this CSS style is being applied to the TD table cell.

```css
.ui-datatable-data td[role="gridcell"]:focus, 
.ui-datatable-data td[role="gridcell"] *:focus, 
.ui-datatable-data td[role="grid"] [tabindex="0"]:focus {
    outline: var(--primary-color, #90caf9);
    outline-style: solid;
    outline-width: 2px;
    border: none;
}
```

**Reply by melloware** [reply]
Go here: https://www.primefaces.org/showcase/ui/data/datatable/basic.xhtml

Click on a cell an then use `ARROW_LEFT/UP/DOWN/RIGHT` to see it in action.

**Reply by hgfrey** [reply]
I tried cell Navigation="false". This does not change the changed appearance of the selectOneMenu elements in a table when the data row is in progress and the element has focus.

The changed behavior is certainly an advantage for blind people when operating a data grid. But why is this related to changing the appearance of the SelectOneMenu element in focus in a table?

**Reply by melloware** [reply]
@hgfrey this selector is clearly picking up your SelectOne Menu.

```css
.ui-datatable-data td[role="gridcell"]:focus, 
.ui-datatable-data td[role="gridcell"] *:focus, 
.ui-datatable-data td[role="grid"] [tabindex="0"]:focus {
    outline: var(--primary-color, #90caf9);
    outline-style: solid;
    outline-width: 2px;
    border: none;
}
```

So tweak the CSS.
