### DISCUSSION TITLE
Menubar collapsing at unexpected value

### DISCUSSION THREAD

**Discussion by Ensar025** [primefaces/community#247] [PrimeNG] [answered]
I was wondering why the [menubar collapses at 960px](https://github.com/primefaces/primeng/blob/master/src/assets/components/themes/md-dark-indigo/theme.css#L4962). The $[lg variable is set to 992px](https://primeflex.org/installation#variables), so I would also expect the menubar to collapse at that value. Because of this, using the lg variable to hide and show items in the menubar leads to some awkward situations where the menubar is not collapsed, but the items in it are hidden.

The menubar at desktop size:
![image](https://github.com/primefaces/community/assets/99197230/53152818-a64a-41c7-beca-29f58042719d)

The menubar at 991px where the menubar itself isn't collapsed but the items with the lg variables are changed:
![image](https://github.com/primefaces/community/assets/99197230/6a47e87f-4c88-499e-8e5d-e9e89b1a7506)

What I would expect the menubar to look like at 991px only happens at 960px or below:
![image](https://github.com/primefaces/community/assets/99197230/038f2a24-b56e-4c1c-b4c2-81480358a63d)

To fix this, I have added the following to my styles.scss file (which is basically copying and pasting [this part of the theme file](https://github.com/primefaces/primeng/blob/master/src/assets/components/themes/md-dark-indigo/theme.css#L4962-L5049) and changing the max-width value):
```scss
@media screen and (max-width: ($lg - 1)) { //only relevant part
  .p-menubar {
    position: relative;
  }

  .p-menubar .p-menubar-button {
    display: flex;
    width: 2.5rem;
    height: 2.5rem;
    color: rgba(255, 255, 255, 0.6);
    border-radius: 50%;
    transition: background-color 0.2s, color 0.2s, box-shadow 0.2s;
  }

  // more content below, but hidden for readability's sake
}
```

It would be nice if we were able to just edit the point where the menubar collapses without having to copy and paste duplicate code, or if the menubar itself used the [variables defined by Primeflex](https://primeflex.org/installation#variables).

I haven't used the dock component yet, but the same [960px is used there](https://github.com/primefaces/primeng/blob/master/src/assets/components/themes/md-dark-indigo/theme.css#L4620).

Thank you in advance.
