### DISCUSSION TITLE
[p-table]The last column of table not fit the width of table when resize column

### DISCUSSION THREAD

**Discussion by ttnnphuoc** [primefaces/community#2471] [PrimeNG]
When I try to resize column in the header of table we have a blank at last column
I'm using

    [resizableColumns]="true" 
    columnResizeMode="expand" 
    
<img width="1396" alt="Screenshot 2024-08-07 at 23 48 02" src="https://github.com/user-attachments/assets/ce7eae33-0ffe-40f2-98f0-b813a5eea8c0">

**Comment by qwadrox** [comment]
I think this is desirable and correct, because what if you had lots of columns with long texts in them? Resizing would be annoyingly hard, you would need to push away a little bit the columns constantly. So `columnResizeMode="expand"`  is useful, and it is desirable that it's changing the table's with. 

What you can do is use CSS to style that blank / white area.

**Reply by qwadrox** [reply]
Maybe you can style the table's wrapper background to look like stripped lines: 
```css
:host ::ng-deep .p-datatable-wrapper {
    background: repeating-linear-gradient(
    0deg,      
    white,  
    white 30px,  
    #f0f0f0 30px,
    #f0f0f0 60px
  );
}
```
Change the px values according to your row height.
