### DISCUSSION TITLE
How to style CascadeSelect component

### DISCUSSION THREAD

**Discussion by umyanl** [primefaces/community#2636] [PrimeNG]
I am using CacadeSelect component for multiple levels, when a choice picked and with long width, then every level is displayed with this wide width. And several levels will be out of display area. Is there any way to style the component so that each level is displayed with its own width that fits the content?

**Comment by qwadrox** [comment]
@umyanl 
Yes, you can do that easily: 

```css
.p-cascadeselect-item-text {
  white-space: nowrap;      /* Prevent text from wrapping to the next line */
  overflow: hidden;         /* Hide overflowed content */
  text-overflow: ellipsis;  /* Display "..." for overflowed text */
  max-width: 200px;         /* Set a maximum width for the element */
}
```

Or you can use JavaScript and trim the data array before you use it.

Here is a complete example for both situations: 
https://stackblitz.com/edit/demges?file=src%2Fapp%2Fcascade-select-basic-demo.ts

**Reply by qwadrox** [reply]
How can you style components? You have different options: https://primeng.org/theming

**Reply by umyanl** [reply]
In my situation, the first two levels have short description, the last level have a long description. When it is initial empty, the component shows everything fine. Once one long choice is picked, every level will show with the width of the newly picked long choice and make the last level or even the second level barely visible.

I forked your demo with a long leaf choice under United States->Florida->Very long very..., once it is picked, the last level is not visible.

Is there any way the the width of each level is assigned separately according to its own contents?

**Reply by qwadrox** [reply]
I don't fully understand what is your requirement. 

<img width="853" alt="image" src="https://github.com/user-attachments/assets/81b984d8-a714-4192-9e71-f1ae86fff0d9">

In the example there was no: United States -> Florida- > Very long very....

Could you please create a sample on stackblitz?

**Reply by qwadrox** [reply]
A picture would be great as well, with some drawing what you expect to be.

**Comment by umyanl** [comment]
![image](https://github.com/user-attachments/assets/94c56d19-fe4e-430d-92a5-63b282f48933)

**Reply by umyanl** [reply]
When a long choice is chosen, all dropdown panels' minimum width is the same as the choice. Even when maximum width is limited, the panel width is not limited, just showing more empty space.

**Reply by umyanl** [reply]
Forked: https://stackblitz.com/edit/demges-y5oxkg?file=src%2Fapp%2Fcascade-select-basic-demo.ts

**Reply by qwadrox** [reply]
<img width="476" alt="image" src="https://github.com/user-attachments/assets/13b05cd3-448e-4ffc-a9bb-0961ddcbb789">

```css
:host ::ng-deep .p-cascadeselect-item-text{
    white-space: nowrap;
    overflow: hidden; 
    text-overflow: ellipsis; 
    max-width: 200px;
}

:host ::ng-deep  .p-cascadeselect-label {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    max-width: 300px;
}

:host ::ng-deep .my-cascadeSelect ::ng-deep div.p-overlay {
  min-width: unset !important;
}

:host ::ng-deep .p-cascadeselect-sublist {
  min-width: unset !important;
}
```

https://stackblitz.com/edit/demges-oo5rzw?file=src%2Fapp%2Fcascade-select-basic-demo.ts

I added more CSS, you can play with it further.
