### DISCUSSION TITLE
[Tree] Node highlight colors

### DISCUSSION THREAD

**Discussion by DKPlugins** [primefaces/community#2724] [PrimeReact] [answered]
Hi.

I need to change the color of the line selection (p-highlight) depending on whether the node is fully or partially selected.
Green for the full node and orange for the partial node.

How can I do this?

**Comment by qwadrox** [comment]
Hi @DKPlugins!

I assumed you wanted to change the colors of the nodes when they're focused. On different level, different colors.
<img width="399" alt="image" src="https://github.com/user-attachments/assets/8bb15810-fde2-4c69-964a-5c4d36cb98ea">

```css
.mytree.p-tree .p-tree-container .p-treenode:focus > .p-treenode-content {
  box-shadow: inset 0 0 0 0.15rem green !important; /* Green */
}

/* Nesting */
.mytree.p-tree
  .p-tree-container
  .p-treenode
  .p-treenode:focus
  > .p-treenode-content {
  box-shadow: inset 0 0 0 0.15rem orange !important; /* Orange */
}

```
Example code:
https://stackblitz.com/edit/t5i47h?file=src%2Findex.css

This approach uses the cascading nature of CSS, but there are many other ways, for instance:

- Applying inline style or classes on the treeNode itself: https://primereact.org/tree/#api.TreeNode 
- Using nth-child
