### DISCUSSION TITLE
DataTable: Horizontal scrollbar on top not bottom

### DISCUSSION THREAD

**Discussion by melloware** [primefaces/community#2757] [PrimeFaces]
I was asked to investigate this and I don't know quite why people want this but if you want a PF DataTable to have the scrollbar on the top of the table and not the bottom you can use this CSS "at your own risk".

```css
.ui-datatable-scrollable-body {
  overflow-x: scroll;
  overflow-y: auto;
  transform: rotateX(180deg);
}

.ui-datatable-scrollable-body table {
  transform: rotateX(180deg);
  width: 100%;
  overflow-x: scroll;
}
```
