### DISCUSSION TITLE
change menu icon avalon theme

### DISCUSSION THREAD

**Discussion by marcelocaser** [primefaces/community#2763] [PrimeFaces Templates] [answered]
How can i custom menu icon like version avalon 2.1.2?

Avalon 3.0.0
![image_2024-09-27_121336692](https://github.com/user-attachments/assets/b256d597-2ac2-490e-8d36-501fc3f09e0a)

Avalon 2.1.2
![image](https://github.com/user-attachments/assets/50b8ea40-58aa-40e5-b405-ecea85be552a)

The "chevron" icon is very disproportionate.

**Comment by melloware** [comment]
I don't own Avalon so i can't see what is going on to help. Sorry.

**Comment by marcelocaser** [comment, marked as answer]
@melloware for now i created the custom sytle:

add style below in _layout_styles.scss:

```css
/* component menu */
.layout-wrapper .layout-menu li a i.menuitem-toggle-icon {
    font-size: 12px;
    font-weight: 700;
}

.layout-wrapper.menu-layout-horizontal .layout-menu-container ul.layout-menu li a .menuitem-toggle-icon {
    margin-left: 4px;
}
```
