### DISCUSSION TITLE
About Paginator  ， can i   add any text before or after the showJumpToPageInput

### DISCUSSION THREAD

**Discussion by xumoqiu** [primefaces/community#2772] [PrimeNG]
About Paginator  ，if i set showJumpToPageInput as true ， can i   add any text before or after the input box

**Comment by qwadrox** [comment]
@xumoqiu 
Hi. 

It is not supported by the component out of the boxed. As I see, none of the provided template options would work for you. In this case, you can use CSS for example or other Angular features to include text after that box: 


```css
 styles: `
        :host ::ng-deep .p-paginator .p-paginator-page-input::after {
            display: flex;
            content: " your after text here"; 
            color: #000;
            margin-left: 10px;
            margin-top: auto;
            margin-bottom: auto;
            font-size: 14px;
        }

        :host ::ng-deep .p-paginator .p-paginator-page-input::before {
            display: flex;
            content: " your before text here"; 
            color: #000;
            margin-right: 10px;
            margin-top: auto;
            margin-bottom: auto;
            font-size: 14px;
        }
    `,
```

<img width="534" alt="image" src="https://github.com/user-attachments/assets/2b77ef9c-de03-4d00-b1a9-63d3b8ae7490">


Demo code: https://stackblitz.com/edit/n1jyy7?file=src%2Fapp%2Fpaginator-basic-demo.ts

You can also manipulate the DOM with JavaScript. In angular, the recommended way is to use renderer 2 https://angular.dev/api/core/Renderer2
