### DISCUSSION TITLE
Remove TabMenu tick gray bar at the bottom

### DISCUSSION THREAD

**Discussion by pierrefroy** [primefaces/community#2933] [PrimeFaces] [answered]
Hi,

I'm trying to style a TabView component in order to remove the tick gray bar showing at the bottom of the component. I inspected the html and the styles and I can't find the origin of this gray bar.

I'm using the code as in the showcase : 

`
<p:tabMenu activeIndex="#{param.i}">
        <p:menuitem value="Home" outcome="/ui/menu/tabMenu" icon="pi pi-fw pi-home">
            <f:param name="i" value="0"/>
        </p:menuitem>
        <p:menuitem value="Calendar" outcome="/ui/menu/tabMenu" icon="pi pi-fw pi-calendar"
                    badge="#{menuBadgeView.badgeModel}">
            <f:param name="i" value="1"/>
        </p:menuitem>
        <p:menuitem value="Edit" outcome="/ui/menu/tabMenu" icon="pi pi-fw pi-pencil"
                    disabled="true">
            <f:param name="i" value="2"/>
        </p:menuitem>
        <p:menuitem value="Documentation" outcome="/ui/menu/tabMenu" icon="pi pi-fw pi-file">
            <f:param name="i" value="3"/>
        </p:menuitem>
        <p:menuitem value="Settings" outcome="/ui/menu/tabMenu" icon="pi pi-fw pi-cog">
            <f:param name="i" value="4"/>
        </p:menuitem>
    </p:tabMenu>
`

Here is the gray bar :

![TabViewScreenshot](https://github.com/user-attachments/assets/4bf4572b-b6d8-4c62-b98d-10c9a446303c)

Primefaces 13.x

Regards,
Pierre Francis

**Comment by melloware** [comment]
here you go

```css
body .ui-tabs.ui-tabs-top>.ui-tabs-nav li.ui-tabs-header,
body .ui-tabs.ui-tabs-top > .ui-tabs-nav::before {
  border-bottom: unset !important;
}
```

**Reply by pierrefroy** [reply]
Thank you! I tried the solution and the selector doesn't affect the TabMenu. I was able to target the top part of the component with this selector, this make the background of the tabs red. But I still can't rearch the lower gray part, below the 2px darker gray border.

`
body .ui-tabmenu .ui-tabmenu-nav {
    background: red;
}
`

**Reply by melloware** [reply]
Add sorry i was using TabView for TabMenu.

```css
body .ui-tabmenu .ui-tabmenu-nav .ui-tabmenuitem {
  border-bottom: unset !important;
}
```
