### DISCUSSION TITLE
remove outline

### DISCUSSION THREAD

**Discussion by Uzeyir9695** [primefaces/community#314] [PrimeVue]
Hello, how can I remove outline when I click on a multiselect box? When select box is activated it sets outline for the current select box.

**Comment by FlipWarthog** [comment]
That's being applied by the specific theme you're using. You can override it by undoing the styling for that specific case, ex.: 
```css
.p-multiselect:not(.p-disabled).p-focus {
  box-shadow: none;
}
```
https://stackblitz.com/edit/amkpec?file=src%2FApp.vue
