### DISCUSSION TITLE
p:picklist with checkbox / height

### DISCUSSION THREAD

**Discussion by AndrewChurchill1970** [primefaces/community#3243] [PrimeFaces] [answered]
picklist component doesn't adjust the height itself correct when checkbox is displayed next to each item. posibillity to set the height of the picklist as responsive attribute does it for width would be usefull.
=>
```css
.ui-picklist.ui-picklist-responsive .ui-picklist-list {
  width: auto;
  **height: auto;**
}
```
