### DISCUSSION TITLE
Ultima 17.0.0: p-table pFrozenColumn has several issues with argb colors

### DISCUSSION THREAD

**Discussion by ThorstenKunz** [primefaces/community#327] [PrimeNG Templates] [answered]
When p-datatable-striped is used all even rows have a translucent background so that during horizontal scrolling the non-frozen columns content is not hidden behind the frozen ones but "merge" with the frozen column content.
Same is true for selectable rows and hovered rows when no p-datatable-striped is used but the hover or selection style is applied to a row.

Seems to happen everywhere were the theme uses an argb color effect to apply a darker shade of grey then to simply used a fixed color.

**Comment by cetincakiroglu** [comment]
Hi,

Could you please share screenshots or screen recordings to demonstrate the issue so we can identify and understand it clearly?

**Comment by ThorstenKunz** [comment]
Its actually pretty easy to replicate with the Ultima Demo code in the download. Simply add `styleClass="p-datatable-striped"` to the "Frozen Columns" Table in tabledemo.component.html and it'll look like this:

![Animation](https://github.com/primefaces/community/assets/30314770/7fb53652-810c-4474-b5b6-14fc5d62bee2)

Same happens when you set `[rowHover]="true"` instead of the striped table:

![Animation2](https://github.com/primefaces/community/assets/30314770/81971bfa-d758-4aa3-b5a1-50442b1e1ae3)

It is also true for other effects that use argb translucency to highlight a row like e.g. row selection.

**Reply by ThoSap** [reply]
I have the exact same issue with MirageNG @cetincakiroglu
@ThorstenKunz as a workaround I fixed it like this in file `src/assets/layout/styles/theme/theme-base/components/data/_datatable.scss`:
```scss
.p-datatable {
  // Custom fix for https://github.com/orgs/primefaces/discussions/327
  &.p-datatable-scrollable {
    .p-datatable-tbody > tr > td.p-frozen-column {
      background: $tableBodyRowBg;
    }
    .p-datatable-tbody > tr:nth-child(even) > td.p-frozen-column {
      background: $tableBodyRowEvenBg;
    }
  }
}
```
