### DISCUSSION TITLE
Using [dt] to theme subcomponents

### DISCUSSION THREAD

**Discussion by JHarrisGTI** [primefaces/community#3335] [PrimeNG]
I am using [scoped tokens](https://primeng.org/theming#scopedtokens) to theme a [multiselect](https://primeng.org/multiselect) component. Multiselect contains a number of checkbox components which I am having trouble styling. Here's the object I'm passing into the multiselect's `[dt]`:

```js
greenTheme = {
	checkboxCheckedBackground: '#849A89',
	colorScheme: {
		light: {
			root: {
				checkedBackground: '#849A89',
			},
			checkbox: {
				checkedBackground: '#849A89',
			},
			primary: {
				color: '#849A89'
			},
			formField: {
				primaryColor: '#849A89',
			}
		}
	},
}
```

None of these do anything. Is there some special trick to accessing subcomponents?

**Comment by JHarrisGTI** [comment]
After further investigation, it doesn't appear that the design token system includes support for theming subcomponents. Instead I'm using this SCSS rule:

```scss
::ng-deep .p-multiselect .p-checkbox-box {
	--p-checkbox-checked-background: var(--p-sage);
	--p-checkbox-border-color: var(--p-sage);
	--p-checkbox-checked-border-color: var(--p-sage);
}
```
('sage' is the color I've defined in my preset, in the `primitive` section.)
