### DISCUSSION TITLE
Add "help" severity to Tag component, to match Button component

### DISCUSSION THREAD

**Discussion by cdrini** [primefaces/community#4085] [PrimeVue]
The Tag component implements the same severity options as the Button component -- _except_ the help severity.

[Button Severity](https://primevue.org/button/#severity):

![Image](https://github.com/user-attachments/assets/44591081-52dd-484e-9fae-54cc4904b039)

[Tag Severity](https://primevue.org/tag/#severity):

![Image](https://github.com/user-attachments/assets/cac67a61-faa6-42a0-9add-78c79e3900eb)

It would be nice if these were consistent, I tried to add the help severity to tag, expecting it to exist since, but no luck!

I implemented it locally with this css for light and dark mode

```css
            .p-tag-help {
                background: var(--p-purple-100);
                color: var(--p-purple-700);
            }

            body.dark-mode .p-tag-help {
                background: color-mix(in srgb,var(--p-purple-500),transparent 84%);
                color: var(--p-purple-300);
            }
```
