### DISCUSSION TITLE
Custom color Slider

### DISCUSSION THREAD

**Discussion by JSoaress** [primefaces/community#749] [PrimeReact] [answered]
Hi, is it possible to customize the color of the Slider handle?

**Comment by melloware** [comment, marked as answer]
Yep...

```css
.p-slider .p-slider-handle {
    background: lightgreen;
    border: 2px solid darkred;
}
```

**Reply by JSoaress** [reply]
thanks! and the bar?

**Reply by FlipWarthog** [reply]
That's the `p-slider` class
```css
.p-slider {
    background: red;
}
```
