### DISCUSSION TITLE
Config value "hideOverlaysOnDocumentScrolling" has no effect on DataTable filter overlays

### DISCUSSION THREAD

**Discussion by mtnair** [primefaces/community#882] [PrimeReact] [answered]
When I set the option "hideOverlaysOnDocumentScrolling" to "false" in "PrimeReactProvider", this option has no effect on overlays shown when opening the menu-style filter overlays in DataTables.
We identified a problem with this in Safari on iOS, where the page is automatically being scrolled to the point where the input is in the middle of the screen when focusing the input field, which hides the filter overlay.
In the following CodeSandbox Demo (forked from the [docs](https://primereact.org/datatable/#advanced_filter)) I added the option "hideOverlaysOnDocumentScrolling" in the main.jsx, but as you can see, the filter overlay is being hidden when you scroll in the table, which also happens in Safari on iOS: https://codesandbox.io/s/primereact-demo-forked-gd2lw2?file=/src/main.jsx:499-549

Am I missing something, is there any workaround for this or should I file a bug report?

**Comment by melloware** [comment, marked as answer]
I fixed your sandbox: https://codesandbox.io/s/primereact-demo-forked-3w4hrh?file=/src/index.css

2 things.
1. Made it PR 10.3.1
2. I fixed your CSS of the `body` element.

```css
body {
  margin: 0px;
  min-height: 100%;
  overflow-x: hidden;
  overflow-y: auto;
  background-color: var(--surface-ground);
  font-weight: normal;
  color: var(--text-color);
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

The BODY has to Overflow for that to work.
